# Chapter 2

## A Single Neuron

In [1]:
input = [1,2,3]
weights = [0.2, 0.8, -0.5]
bias = 2

In [2]:
output = (input[0] * weights[0] +
          input[1] * weights[1] +
          input[2] * weights[2] +
          bias)

print(output)

2.3


In [3]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = (inputs[0]*weights[0] +
          inputs[1]*weights[1] +
          inputs[2]*weights[2] +
          inputs[3]*weights[3] + 
          bias)

print(output)

4.8


## A Layer of Neurons

In [4]:
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
            # Neuron 1:
            inputs[0]*weights1[0] +
            inputs[1]*weights1[1] +
            inputs[2]*weights1[2] +
            inputs[3]*weights1[3] + bias1,
    
            # Neuron 2:
            inputs[0]*weights2[0] +
            inputs[1]*weights2[1] +
            inputs[2]*weights2[2] +
            inputs[3]*weights2[3] + bias2,
    
            # Neuron 3:
            inputs[0]*weights3[0] +
            inputs[1]*weights3[1] +
            inputs[2]*weights3[2] +
            inputs[3]*weights3[3] + bias3
        ]

print(outputs)

[4.8, 1.21, 2.385]


In [5]:
# My implementation 

inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]
          ]

biases = [2, 3, 0.5]

output = []
for neuron_weights, neuron_biases in zip(weights, biases):
    neuron_output = 0
    for i in range(len(neuron_weights)):
        neuron_output += inputs[i] * neuron_weights[i]
    output.append(neuron_output + neuron_biases)

print(output)

[4.8, 1.21, 2.385]


In [6]:
print(output)

[4.8, 1.21, 2.385]


In [7]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
[0.5, -0.91, 0.26, -0.5],
[-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# Output of current layer
layer_outputs = []
# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # Zeroed output of given neuron
    neuron_output = 0
    # For each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron's output variable
        neuron_output += n_input*weight
    # Add bias
    neuron_output += neuron_bias
    # Put neuron's result to the layer's output list
    layer_outputs.append(neuron_output)
    
print(layer_outputs)

[4.8, 1.21, 2.385]


## Tensors, Arrays and Vectors

In [8]:
a_tensor = [[[1,5,6,2],
             [3,2,1,3]],
            [[5,2,1,2],
             [6,4,8,4]],
            [[2,8,5,3],
             [1,1,9,4]]
           ]

In [9]:
import numpy as np

np.array(a_tensor).shape

(3, 2, 4)

## Dot Product and Vector Addition

A dot product of two vectors is a sum of products of consecutive vector elements. Both vectors
must be of the same size (have an equal number of elements).

In [10]:
a = [1,2,3]
b = [2,3,4]

dot_product = (a[0]*b[0] + 
               a[1]*b[1] + 
               a[2]*b[2])

print(dot_product)

20


In [11]:
a = np.array(a)
b = np.array(b) 

dot_product = a @ b
print(dot_product)

20


In [12]:
dot_product = b @ a
print(dot_product)

20


In [13]:
dot_product = a.dot(b)
print(dot_product)

20


In [14]:
dot_product = np.dot(a, b)
print(dot_product)

20


## A Single Neuron with NumPy

In [15]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(inputs, weights) + bias

print(outputs)

4.8


## A Layer of Neurons with NumPy

In [16]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [ 
            [0.2, 0.8, -0.5, 1],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]
          ]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


## A Batch of Data and Matrix Product

In [18]:
a = list(range(1, 4))
a

[1, 2, 3]

In [19]:
np.array(a)

array([1, 2, 3])

In [25]:
np.expand_dims(np.array(a), axis=0)

array([[1, 2, 3]])

In [26]:
np.expand_dims(np.array(a), axis=0).shape

(1, 3)

In [27]:
np.expand_dims(np.array(a), axis=1)

array([[1],
       [2],
       [3]])

In [28]:
np.expand_dims(np.array(a), axis=1).shape

(3, 1)

In [32]:
biases

[2.0, 3.0, 0.5]

In [34]:
np.array(biases).T

array([2. , 3. , 0.5])

In [35]:
np.array(biases).T.shape

(3,)

In [37]:
np.array(biases).shape

(3,)

In [38]:
import numpy as np
a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

print(np.dot(a, b))

[[20]]


In [43]:
import numpy as np
inputs = [  
            [1.0, 2.0, 3.0, 2.5],
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]
         ]
weights = [ 
            [0.2, 0.8, -0.5, 1.0],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]
          ]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(inputs, np.array(weights).T) + biases
print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [44]:
# Same resule but we will not use this as we have to take transpose 2 times 
np.dot(weights, np.array(inputs).T).T + biases

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

As you can see, our neural network takes in a group of samples (inputs) and outputs a group of
predictions. If you’ve used any of the deep learning libraries, this is why you pass in a list of
inputs (even if it’s just one feature set) and are returned a list of predictions, even if there’s only
one prediction.

# Chapter 3

### Adding Layers